<?php require_once __DIR__.'/includes/functions.php';$slug=$_GET['slug']??''; try {
    $s=db()->prepare("SELECT a.*,d.name destination_name FROM attractions a JOIN destinations d ON d.id=a.destination_id WHERE a.slug=? AND a.status='active'");
    $s->execute([$slug]);
    $a=$s->fetch();
} catch (Throwable $error) {
    $fallback=['heritage-museum'=>['name'=>'Heritage Museum','destination_name'=>'Heritage District','short_description'=>'A hands-on journey through local history.','description'=>'Discover objects, photographs and stories preserved by the community.','main_image'=>'','maps_url'=>'','youtube_url'=>''],'forest-lookout'=>['name'=>'Forest Lookout','destination_name'=>'Nature Escape','short_description'=>'A panoramic nature viewpoint.','description'=>'Follow the trail to a scenic lookout and enjoy the landscape.','main_image'=>'','maps_url'=>'','youtube_url'=>''],'crafts-market'=>['name'=>'Crafts Market','destination_name'=>'Cultural Village','short_description'=>'Meet makers and discover handmade treasures.','description'=>'Browse handmade goods and meet the people behind local traditions.','main_image'=>'','maps_url'=>'','youtube_url'=>'']];
    $a=$fallback[$slug]??null;
} if (!$a) {
    http_response_code(404);
    exit('Attraction not found');
}$pageTitle=$a['name'];$video=youtube_id($a['youtube_url']);require __DIR__.'/includes/header.php';?><section class="container py-5"><a href="<?=url('attractions.php')?>">&larr; All attractions</a><div class="row g-5 mt-2"><div class="col-lg-6"><img class="img-fluid rounded-4 shadow" src="<?=$a['main_image'] ? asset($a['main_image']) : asset('images/hero.svg')?>" alt="<?=e($a['name'])?>"></div><div class="col-lg-6"><small class="text-success"><?=e($a['destination_name'])?></small><h1 class="section-title"><?=e($a['name'])?></h1><p class="lead"><?=e($a['description'])?></p><?php if ($a['opening_hours']):?><p><i class="fa-regular fa-clock"></i> <?=e($a['opening_hours'])?></p><?php endif;?><?php if ($a['maps_url']):?><a class="btn btn-success" target="_blank" rel="noopener" href="<?=e($a['maps_url'])?>"><i class="fa-solid fa-map"></i> View on Google Maps</a><?php endif;?><?php if ($video):?><a class="btn btn-outline-danger" target="_blank" rel="noopener" href="https://www.youtube.com/watch?v=<?=e($video)?>"><i class="fa-brands fa-youtube"></i> Watch video</a><?php endif;?></div></div></section><?php require __DIR__.'/includes/footer.php';?>
