<?php require_once __DIR__ . '/includes/functions.php'; $pageTitle='Destinations'; $q=trim($_GET['q']??''); try {
    $stmt=db()->prepare("SELECT d.*,c.name category_name FROM destinations d LEFT JOIN categories c ON c.id=d.category_id WHERE d.status='active' AND (d.name LIKE ? OR d.short_description LIKE ?) ORDER BY d.name");
    $stmt->execute(["%$q%","%$q%"]);
    $items=$stmt->fetchAll();
} catch (Throwable $error) {
    $items = $q ? [] : [['name'=>'Heritage District','slug'=>'heritage-district','location'=>'Demo City','short_description'=>'Stories, architecture and living culture.'],['name'=>'Nature Escape','slug'=>'nature-escape','location'=>'Demo City','short_description'=>'Green trails and open skies.'],['name'=>'Cultural Village','slug'=>'cultural-village','location'=>'Demo City','short_description'=>'Crafts, food and local traditions.']];
} require __DIR__.'/includes/header.php'; ?>
<section class="page-header"><div class="container"><div class="eyebrow">EXPLORE THE WORLD AROUND YOU</div><h1>Destinations</h1><p class="lead mb-0">Find your next story, from historic streets to quiet natural escapes.</p></div></section>
<section class="container filter-bar"><div class="card p-3"><form class="row g-2 align-items-center"><div class="col-md"><input class="form-control form-control-lg" name="q" value="<?=e($q)?>" placeholder="Search destinations"></div><div class="col-auto"><button class="btn btn-success btn-lg px-4"><i class="fa-solid fa-magnifying-glass"></i> Search</button></div></form></div></section>
<section class="container py-5"><div class="row g-4"><?php foreach ($items as $d): ?><div class="col-md-6 col-lg-4"><div class="card h-100 p-4 feature-card"><small class="text-success fw-bold"><i class="fa-solid fa-location-dot"></i> <?=e($d['location'] ?: 'Discover nearby')?></small><h3 class="mt-3"><?=e($d['name'])?></h3><p><?=e($d['short_description'])?></p><a class="btn btn-success mt-auto align-self-start" href="<?=url('destination.php?slug='.urlencode($d['slug']))?>">Explore <i class="fa-solid fa-arrow-right ms-1"></i></a></div></div><?php endforeach; ?><?php if (!$items): ?><div class="col-12"><div class="empty-state"><i class="fa-solid fa-map-location-dot fa-2x mb-3"></i><h3>No destinations found</h3><p>Try a different search term or check back soon.</p></div></div><?php endif; ?></div></section><?php require __DIR__.'/includes/footer.php'; ?>
